[package]
name = "v8find4rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs_io = "0.1.7"
exe = "0.4.2"
regex = "1.5.4"
itertools = "0.10.1"
lazy_static = "1.4.0"
bitness = "0.4.0"